version: 2

project_name: craft-auto-routing

before:
  hooks:
    - go mod tidy

builds:
  - id: craft-auto-routing
    main: ./cmd/craft-auto-routing
    binary: craft-auto-routing
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: craft-auto-routing
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: ucpr
    name: craft-auto-routing
